export const LOADING_SPECIALS = 'LOADING_SPECIALS'
export const SET_SPECIALS = 'SET_SPECIALS'
export const FAILED_LOADING_SPECIALS = 'FAILED_LOADING_SPECIALS'
export const LOADED_SPECIALS = 'LOADED_SPECIALS'